### ISSUE TITLE
Sitreps and Chosen panels visible on mission infiltration screens

### ISSUE THREAD

**Issue by pledbrook** [pledbrook/lwotc#17]
See #16 for a screenshot demonstrating the problem. The screen is displaying panels that don't apply to the mission, i.e. active Chosen and sitreps. I tried to fix the sitreps panel [here](https://github.com/pledbrook/lwotc/blob/master/LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_LWMissionSources.uc#L73), but it doesn't seem to be working.

**Comment by tracktwo** [comment]
This one should be resolved now too, I think.

**Comment by pledbrook** [comment]
OK, cool. I just want to check before closing.
