### ISSUE TITLE
Rescue contacts mission crashes on load during campaign

### ISSUE THREAD

**Issue by pledbrook** [pledbrook/lwotc#45]
I can't seem to reproduce this in skirmish mode or when forcing it as a debug mission. But there's definitely something wrong.

**Comment by pledbrook** [comment]
This is apparently a problem with having multiple objectives, with each objective being a reward (rebel or soldier).

I basically need to port the `DLCInfo.GetNumObjectivesToSpawn()` hook used by `XComTacticalMissionManager` from the old LW2 code to the community highlander.

**Comment by Witt-Github** [comment]
Was this ever fully resolved? I think I'm having the same issue. Can open a new ticket if you'd like.
