### ISSUE TITLE
Unable to start a campaign with the mod enabled.

### ISSUE THREAD

**Issue by MajorEvil** [pledbrook/lwotc#66]
I have tried everything possible, but whenever I start the game with the launcher, it does not give me the option to start a LWOTC campaign at all. All the game show's me is the menu's tactical and stratagy at the start menu screen, meaning I can not run the game at all.
![Bug report](https://user-images.githubusercontent.com/49344869/55687099-eaa62400-5960-11e9-90c1-e6e704c14f63.JPG)

**Comment by pledbrook** [comment]
That's the debug starting screen. Are you sure you aren't launching the game with different options when you run with this mod installed?

**Comment by MajorEvil** [comment]
I am launching the game normally via the xcom 2 WOTC launcher. I can be positive that I am not launching it with differant options. I am running it with LWOTC only for play testing.

**Comment by GitWadeanthony** [comment]
MajorEvil did you try doing this
"Find your Xcom2.exe, right-click and open Properties, in Path add -noRedScreens -review, so it looks like
**...\Xcom2.exe" -noRedscreens -review**"

Info taken from this: https://www.reddit.com/r/Xcom/comments/44fhnp/xcom2_how_to_get_out_of_debug_mode/

**Comment by MajorEvil** [comment]
UPDATE: After numerous attempts to get the mod to run, I have Somehow managed to succeed. I can't be sure what was the cause of the problem was though that was preventing me from launching LWOTC I am afraid. All I did was a fresh Re-Install the game on a separate hard drive.

**Comment by pledbrook** [comment]
Glad it's running, but sorry you're still having issues. The only other suggestion I have is to use the alternative mod launcher, which doesn't mess around with launch arguments. It uses the ones you configure.
